version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
#    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sample_demo_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
